
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DISPLAY = 2;
  public static final int LBRACKET = 33;
  public static final int LPAREN = 28;
  public static final int INT = 13;
  public static final int PRINTLN = 20;
  public static final int MINUS = 22;
  public static final int STATIC = 5;
  public static final int RPAREN = 29;
  public static final int NOT = 27;
  public static final int SEMICOLON = 30;
  public static final int AND = 24;
  public static final int LESSTHAN = 25;
  public static final int COMMA = 36;
  public static final int CLASS = 3;
  public static final int PLUS = 21;
  public static final int MAIN = 7;
  public static final int IF = 17;
  public static final int THIS = 10;
  public static final int DOT = 35;
  public static final int EOF = 0;
  public static final int BOOLEAN = 14;
  public static final int RETURN = 9;
  public static final int RBRACKET = 34;
  public static final int TRUE = 15;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int BECOMES = 23;
  public static final int VOID = 6;
  public static final int TIMES = 26;
  public static final int LBRACE = 31;
  public static final int ELSE = 18;
  public static final int WHILE = 19;
  public static final int PUBLIC = 4;
  public static final int RBRACE = 32;
  public static final int EXTENDS = 8;
  public static final int STRING = 12;
  public static final int FALSE = 16;
  public static final int IDENTIFIER = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DISPLAY",
  "CLASS",
  "PUBLIC",
  "STATIC",
  "VOID",
  "MAIN",
  "EXTENDS",
  "RETURN",
  "THIS",
  "NEW",
  "STRING",
  "INT",
  "BOOLEAN",
  "TRUE",
  "FALSE",
  "IF",
  "ELSE",
  "WHILE",
  "PRINTLN",
  "PLUS",
  "MINUS",
  "BECOMES",
  "AND",
  "LESSTHAN",
  "TIMES",
  "NOT",
  "LPAREN",
  "RPAREN",
  "SEMICOLON",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "DOT",
  "COMMA",
  "IDENTIFIER"
  };
}

